# Build settings
gems:
  - jemoji
  - jekyll-paginate

title: 'Shane da Silva'
description: 'Coding by the woods'

email: 'shane@dasilva.io'
logo: '/assets/images/face.jpg'
cover: '/assets/images/computers.jpg'

name: 'Shane da Silva'
author: 'Shane da Silva'
author_image: "/assets/images/face.jpg"

paginate: 6

url: 'https://shane.io'
baseurl: ""
twitter_handle: '@shanedasilva'

social:
  - icon: twitter
    url: 'https://twitter.com/shanedasilva'
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

  - icon:	github
    url:	https://github.com/sds
    desc:	Check out my code
    share_url:
    share_title:
    share_link:

exclude:
  - vendor
  - Gemfile
  - Gemfile.lock
  - README.md
